# Running your first Jupyter notebook

## Some basics

There are two types of cells:
- Markdown cells
- Julia cells

- `Shift`+`Enter` runs a cell
- When a cell is only selected (not in edit mode), we can use these shortcuts:
  - A: create a cell *above* the active cell
  - B: create a cell *below* the active cell
  - DD: removes the active cell
- You can select an installed Kernel to be run.
  - Python can also be used in these notebooks.

Some basic markdown syntax also works here, e.g. use # to declare titles and subtitles:
# Title
## Subtitle
### Subsubtile
#### Subsubsubtile ...
Or you can put latex equations between '$$'s to display them.
$$\alpha^2 + \frac{\beta^2}{\pi^3}$$
You can use '-' (1.) at the begining of the line to make a bullet (numbered) list.
- bullet list
1. numbered list

## Running a cell:
Press `Shift`+`Enter` to execute the current cell. Julia automatically prints the output of the last line of the cell.

In [1]:
2 * 2
3 * 2

6

In [2]:
# Use '#' to comment a line
# Use ; at the end of the command to not print its output
2 * 2
3 * 2;

## Getting documentation about a function
Use @doc macro at the begining of the line to get its documentation. In REPL you can just start the line with '?' instead.

In [19]:
@doc sqrt

```
sqrt(x)
```

Return $\sqrt{x}$. Throws [`DomainError`](@ref) for negative [`Real`](@ref) arguments. Use complex negative arguments instead. The prefix operator `√` is equivalent to `sqrt`.

See also: [`hypot`](@ref).

# Examples

```jldoctest; filter = r"Stacktrace:(\n \[[0-9]+\].*)*"
julia> sqrt(big(81))
9.0

julia> sqrt(big(-81))
ERROR: DomainError with -81.0:
NaN result for non-NaN input.
Stacktrace:
 [1] sqrt(::BigFloat) at ./mpfr.jl:501
[...]

julia> sqrt(big(complex(-81)))
0.0 + 9.0im

julia> .√(1:4)
4-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
```

```
sqrt(A::AbstractMatrix)
```

If `A` has no negative real eigenvalues, compute the principal matrix square root of `A`, that is the unique matrix $X$ with eigenvalues having positive real part such that $X^2 = A$. Otherwise, a nonprincipal square root is returned.

If `A` is real-symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the square root.   For such matrices, eigenvalues λ that appear to be slightly negative due to roundoff errors are treated as if they were zero. More precisely, matrices with all eigenvalues `≥ -rtol*(max |λ|)` are treated as semidefinite (yielding a Hermitian square root), with negative eigenvalues taken to be zero. `rtol` is a keyword argument to `sqrt` (in the Hermitian/real-symmetric case only) that defaults to machine precision scaled by `size(A,1)`.

Otherwise, the square root is determined by means of the Björck-Hammarling method [^BH83], which computes the complex Schur form ([`schur`](@ref)) and then the complex square root of the triangular factor. If a real square root exists, then an extension of this method [^H87] that computes the real Schur form and then the real square root of the quasi-triangular factor is instead used.

[^BH83]: Åke Björck and Sven Hammarling, "A Schur method for the square root of a matrix", Linear Algebra and its Applications, 52-53, 1983, 127-140. [doi:10.1016/0024-3795(83)80010-X](https://doi.org/10.1016/0024-3795(83)80010-X)

[^H87]: Nicholas J. Higham, "Computing real square roots of a real matrix", Linear Algebra and its Applications, 88-89, 1987, 405-430. [doi:10.1016/0024-3795(87)90118-2](https://doi.org/10.1016/0024-3795(87)90118-2)

# Examples

```jldoctest
julia> A = [4 0; 0 4]
2×2 Matrix{Int64}:
 4  0
 0  4

julia> sqrt(A)
2×2 Matrix{Float64}:
 2.0  0.0
 0.0  2.0
```
